version: '3'

services:

  ######################################################################
  # KAFKA AND ZOOKEEPER________________________________________________#
  ######################################################################

  ######################################################################
  # PRODUCER___________________________________________________________#
  ######################################################################

  kfkApiProd01:
    container_name: kfkApiProd01
    environment:
      - bhvList=producer
      - groupId=gId_=group_kfkApiProd01
      - appId=app_kfkApiProd01
      - bhv0_topic=user.brandao.t1
      - bhv0_bootstrapServers=kafka-1:19092
      - bhv0_sleep=200
    image: kafka_client_bootstrap:1.0.0
    networks:
      - net-backend
    ports:
      - "3601:3601"

  #######################################################################
  ## CONSUMER___________________________________________________________#
  #######################################################################

  kfkApiCons01:
   container_name: kfkApiCons01
   environment:
     - bhvList=consumer;consumer;consumer
     - groupId=group_kfkApiCons01
     - appId=app_kfkApiCons01
     # Thread 0
     - bhv0_topic=user.brandao.t2
     - bhv0_bootstrapServers=data-science_kafka-1:9092;data-science_kafka-2:29092;data-science_kafka-3:39092
     # Thread 1
     - bhv1_topic=user.brandao.t2
     - bhv1_bootstrapServers=data-science_kafka-1:9092;data-science_kafka-2:29092;data-science_kafka-3:39092
     # Thread 2
     - bhv2_topic=user.brandao.t2
     - bhv2_bootstrapServers=data-science_kafka-1:9092;data-science_kafka-2:29092;data-science_kafka-3:39092
   image: kafka_client_bootstrap:1.0.0
   networks:
     - data-science_net-backend
   ports:
     - "3621:3621"

 #####################################################################
 # STREAM____________________________________________________________#
 #####################################################################

  kfkApiStream01:
   container_name: kfkApiStream01
   environment:
     - bhvList=stream
     - groupId=gId_=group_kfkApiStream01
     - appId=app_kfkApiStream01
     - bhv0_topic_IN=user.brandao.t1
     - bhv0_topic_OUT=user.brandao.t2
     - bhv0_bootstrapServers=data-science_kafka-1:9092;data-science_kafka-2:29092;data-science_kafka-3:39092
   image: kafka_client_bootstrap:1.0.0
   networks:
     - data-science_net-backend
   ports:
     - "3611:3611"
